### ISSUE TITLE
Allow translation of database records

### ISSUE THREAD

**Issue by tassia** [tiagovaz/saskatoon#10]
Using easymode or anything else that works.

**Comment by tassia** [comment]
if too hard, hardcode translatable choices so that they are translated with gettext

**Comment by tassia** [comment]
At least TreeType, EquipmentType and HarvestStatus should have some translatable fields.

**Comment by tassia** [comment]
Using modeltranslation: http://django-modeltranslation.readthedocs.io

**Comment by tassia** [comment]
Fixed by commit 393536302b23b7f81dfff72c7d07458fa4f82969

**Comment by RignonNoel** [comment]
Oh nice! How do we use this new feature ? 

We just display attributs of the model and i18n load the good data in function of the langage selectionned, or we need a special manipulation ?

**Comment by tassia** [comment]
You need to register the model and fields in the app/translation.py file and it will add columns to the table for each language.
In the site, you just need to change the language selectioned. Have you tried it?
I'll upload a fixtures files with translations in a while, but for now, you can create translation through the admin forms.
Cheers,

Tassia.
