### ISSUE TITLE
Include "My activities" as a session of the Dashboard 

### ISSUE THREAD

**Issue by tassia** [tiagovaz/saskatoon#12]

**Comment by tassia** [comment]
This is the log of activities, and apart from that, we should also have a session "My harvests"

**Comment by RignonNoel** [comment]
- My harvest as pick-leader
- My harvest as picker
- Request in waiting

For the rest, we need to implement a system of notification in the plateforme to detect if user already show the information (and don't display a refused request 1 week if he know the result)

**Comment by tristanlatr** [comment]
Moved to https://github.com/LesFruitsDefendus/saskatoon-ng/issues/2
