### ISSUE TITLE
Add equipment inventory

### ISSUE THREAD

**Issue by rliveanu** [tiagovaz/saskatoon#129]
• keep an inventory listed in Saskatoon for each equipment point
• "reserve" entire kit at a location-- if you want only specific parts, get in contact with the person with the original "reservation" directly
• system should alert that there is a conflict of equipment when a second   pickleader tries to use the same equipment as someone else

**Comment by tassia** [comment]
As discussed recently with the collective, the full inventory list is not necessary, and keeping it up-to-date might be difficult. But we should have a list of equipment points, and each harvest would have a field "equipment from". Choosing an equipment point would "reserve" the whole kit on that location, and when a second pick is schedule for that same point within, let's say a 6h window, the system should alert the pick leader of the conflict, and ask for direct communication with the other pick leader to avoid conflict.
