### ISSUE TITLE
Implement on-the-fly harvest statuses

### ISSUE THREAD

**Issue by tassia** [tiagovaz/saskatoon#15]
Those are the status not stored in the database, but used for coloring the calendar:

* "Urgent", if:
    Orphan and pick date approaching (< 2 weeks)
    Scheduled and pick date approaching (< 2 days)
* "Happening today", if "ready" and due date = today

**Comment by RignonNoel** [comment]
Creation of method in the model. And just use ```is_urgent()``` and ```is_happening()``` in the view of view who get the JSON to upgrade data in the JSON
