### ISSUE TITLE
Saskatoon: "Harvests" tab generates an empty list

### ISSUE THREAD

**Issue by mattsarrasin** [tiagovaz/saskatoon#150]
When we click on "Harvests" in the sidebar, the list of harvests comes up empty. This is a relatively recent change (within the past month maybe). At first I thought it was intentionally done to clear out all of the 2016 harvests before we start creating new harvests for 2017. But new harvests are being created for 2017, and they aren't showing up under Harvests. However, they do show up in the Calendar and can also be accessed via the Property.

**Comment by tiagovaz** [comment]
Hi Matt, I've fixed that after Julia had reported it to @tech, so I'm closing this issue.
