### ISSUE TITLE
Cleaning and adapting to best django practices

### ISSUE THREAD

**Issue by tassia** [tiagovaz/saskatoon#16]

**Comment by RignonNoel** [comment]
- [ ] [pep8 python](https://www.python.org/dev/peps/pep-0008/)
 - [ ] [TravisCI](https://travis-ci.org/)
 - [ ] [Coveralls](http://coveralls.io/)
 - [ ] [CCBV](ccbv.co.uk)
 - [ ] Split application
 - [ ] I18N
 - [ ] urls routage

**Comment by tristanlatr** [comment]
Moved to https://github.com/LesFruitsDefendus/saskatoon-ng/issues/3
