### ISSUE TITLE
In property model equipment vs equipment model

### ISSUE THREAD

**Issue by RignonNoel** [tiagovaz/saskatoon#18]
In the property model we have a ```ManyToManyField``` to ```EquipmentType``` but the verbose name is ```Equipment```.

It must be a foreign key to Equipment no? 

```
    equipment = models.ManyToManyField(
        'EquipmentType',
        verbose_name=_("Equipment")
    )
```

**Comment by tassia** [comment]
Yes, foreign key to Equipment.
Equipment should have the fields: Name, Equipment Type, Description.

**Comment by tassia** [comment]
Equipment now carries property and actor as foreign key and EquipmentAtProperty model was removed.
