### ISSUE TITLE
We can choice all type of treeType when we create a new harvest

### ISSUE THREAD

**Issue by RignonNoel** [tiagovaz/saskatoon#19]
We must have only `TreeType` of the `Property`

**Comment by tassia** [comment]
When we have our own form we should check, for the moment, we can live with the fact that inconsistency might happen. For v0.2 release, we should do a batch check of consistency of all records in the database.

**Comment by tristanlatr** [comment]
I think that's been resolved. I've just checked and I'm able to select from the 30 TreeTypes when creating a harvest. With version 2.0

**Comment by tristanlatr** [comment]
@tassia can you confirm ? Thanks
