### ISSUE TITLE
Handle harvest due date based on history of harvests

### ISSUE THREAD

**Issue by tassia** [tiagovaz/saskatoon#22]
- Maybe create fields:
  - Expected due date (last year date or owner report, can be null)
  - TreeType season start: maybe instead of static it could carry the value of first harvest of last year?

Discussion: how would be the best way to handle this field?

**Comment by tassia** [comment]
Expected date will use the same Start_date field. If it is not given at the creation, the closest "general" date of the list of fruits trees should be used as the start_date. So in practice, the date will never be null

**Comment by tristanlatr** [comment]
Moved to https://github.com/LesFruitsDefendus/saskatoon-ng/issues/4
