### ISSUE TITLE
Add to property details

### ISSUE THREAD

**Issue by tassia** [tiagovaz/saskatoon#27]
Telephone,email, comments and language preference

**Comment by tassia** [comment]
Noel, we would appreciate you help here.
We are having trouble to handle owner attributes on templates. The owner (actor) can be Person or Organization and those classes have a different set of attributes.

**Comment by RignonNoel** [comment]
Hi @tassia 

I think [this method](http://stackoverflow.com/questions/5427809/django-template-object-type) is a good solution.

---
### Filter : 
```
@register.filter
def classname(obj):
    return obj.__class__.__name__
```
### Template :
```
{% with actor|classname as modelclass %}
{% if modelclass == "Person" %}
It's a person!
{% elif modelclass == "Organization" %}
It's an organization
{% endif %}
{% endwith %}
```

**Comment by tassia** [comment]
since return obj.__class__.__name__ always return actor, no matter if it is a Person or Organization, my workaround was to try to access its Person object and catch the error if it is in fact an Organization object
