### ISSUE TITLE
Create pick_leader filter for person

### ISSUE THREAD

**Issue by tassia** [tiagovaz/saskatoon#28]
maybe this is what "is_staff" means?

**Comment by RignonNoel** [comment]
Indeed, we can use ```staff``` or create a new django ```group```.

---

Note : ```staff``` can connect to the admin panel, but you can change permissions to limit action on the panel.

**Comment by tassia** [comment]
the filter is working for choosing harvest pick_leader (only staff AuthUser is listed as possible pick_leader), but the filter for harvest listing does not work when we use an external form

**Comment by RignonNoel** [comment]
It's what you want ?
```
class HarvestFilter(django_filters.FilterSet):
    status = forms.ModelChoiceField(queryset=HarvestStatus.objects.all(), required=False)
    pick_leader = forms.ModelChoiceField(queryset=AuthUser.objects.filter(is_staff=True), required=False)

    class Meta:
        model = Harvest
        fields = ['status', 'pick_leader', 'is_active', ]

```

You don't use the form, and just create directly field in the filter.

**Comment by tassia** [comment]
Declaring fields inside the filter does not work, the queryset is not executed. Changing the view solved the problem.
