### ISSUE TITLE
Add help to harvest status

### ISSUE THREAD

**Issue by tassia** [tiagovaz/saskatoon#29]
the meaning of each possible status

**Comment by tiagovaz** [comment]
I couldn't find how to make it with bootstrap_form using django 'help_text' feature :\

**Comment by RignonNoel** [comment]
To show dynamically the helper in function of the status selected i might use JS function to change a helper div in the template page

**Comment by tristanlatr** [comment]
Moved to https://github.com/LesFruitsDefendus/saskatoon-ng/issues/6
