### ISSUE TITLE
Notification of request

### ISSUE THREAD

**Issue by tassia** [tiagovaz/saskatoon#31]
new request for participation should send an email to the pick leader

**Comment by tiagovaz** [comment]
That's done and seems to work well.

For reference, the proposed French version is:

Bonjour AAA,

Ceci est une demande de XXX pour participer à la cueillette #Z à 'yyyyy'.

Nom complet:
Courriel:
Téléphone:
Commentaire:

Merci de contacter XXX directement puis d'enregistrer cette demande via:

http://saskatoon.lesfruitsdefendus.org/harvest/ID

Salutations,
--
Le système de récolte XYZW
