### ISSUE TITLE
Implement equipment reservation workflow

### ISSUE THREAD

**Issue by tassia** [tiagovaz/saskatoon#35]
The same equipment can not be reserved by more than one harvest simultaneously. Maybe connected with map, or available equipment being listed by proximity with property location, but not needed at first.

**Comment by RignonNoel** [comment]
We need to implement a model method to check if equipment is reserved or not between two date. 

```is_reserved(begin_datetime, end_datetime)```

For the rest, have you a detail of the workflow ? The list of action to reserve an equipment. Or we make a first test and we see after ?

**Comment by tassia** [comment]
The equipment will be reserved through the HarvestDetail view, and will trigger the check. There should be a list of all active reservations (for scheduled picks). Also, the harvests that reserved each equipment should be shown in the table of Equipment list.

**Comment by tristanlatr** [comment]
This feature is wanted for a long time! We should also consider the fact that several trailer can be stored in a single equipment point. Admins should be able to add / remove / add details to Equipment infos. The way I see things, we can borrow 4 things from the equipment point: bike(+helmet!), trailer(+tools), harvest equipment(pols, gloves, scissors, etc.), ladder. Most of the time, people would take the whole bundle, but sometime they don't need the bike/trailer or ladder, the workflow should consider this aspect. In any case, this would require to create new tables in the database. It's certainly a nice to have for 2021
