### ISSUE TITLE
Creation of 'develop' branch

### ISSUE THREAD

**Issue by RignonNoel** [tiagovaz/saskatoon#37]
Now that the project is in alpha. It might be well to follow the git flow.

So we can create a develop branch and make pull-request on this branch to avoid bug when we work on the same time.

[Example of Git flow](http://nvie.com/posts/a-successful-git-branching-model/)

**Comment by tassia** [comment]
Great Noël, can you take care of that?
I'm not used to the git flow, but I'll read the documentation you have linked above.
Thanks!
