### ISSUE TITLE
Property address could use the actor personal address

### ISSUE THREAD

**Issue by tassia** [tiagovaz/saskatoon#40]
Add a checkbox to the New Property form in order to use the same address as the actor personal address

**Comment by tassia** [comment]
We have changed how it works, there is no more address model, maybe validate the new model and close the issue.

**Comment by RignonNoel** [comment]
In behaviours.py (create this file in the app of your choice):

```
from django.db import models

class Addressable(models.Model):
    # Create your field of address here
    # ex : create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True
```

To use :
```
class NameOfYourClass(Addressable, models.Model):
```

**Comment by tassia** [comment]
Finally, the "addressable" inheritance will not work because we want those fields to be compulsory for Property and not mandatory for Actor (Person or Organization).
