### ISSUE TITLE
Create view for listing requests for participation

### ISSUE THREAD

**Issue by tassia** [tiagovaz/saskatoon#6]

**Comment by tassia** [comment]
Pick leaders will be able to view all the requests for the picks he/she is leading and accept requests up to the number of participars required. In the listing, should make evident the fields first_pick and helper_picker, since they interfere in the pick leader choice.

**Comment by RignonNoel** [comment]
For the moment the model contain that:
```
    pick_leader = models.ForeignKey(
        'member.AuthUser',
        null=True,
        blank=True,
        verbose_name="Pick leader"
    )
```

Can we delete ```null = True``` and ```blank = True``` before ?

**Comment by tassia** [comment]
no we can't, cause when the harvest is created, there is no pick_leader yet.
pick_leader assign themselves to harvests (they "adopt" the harvest), according to their convenience.

**Comment by RignonNoel** [comment]
We've decided to just add this on the dashboard for the pickleader.
We can also see this information on harvest detail
