### ISSUE TITLE
Auth user does not accept person whose name has acent

### ISSUE THREAD

**Issue by tassia** [tiagovaz/saskatoon#84]
Example: "Larivière"
The person is created, but when tried to assign it to auth_user got error "unicode cannot decode character"

**Comment by tassia** [comment]
Maybe it is just something with the admin interface. If the person is already created and assigned to auth_user, we can edit the name and include accents with no problem.

**Comment by tiagovaz** [comment]
Fixed. Missed a "u" (unicode) in the __str__ return()
