### ISSUE TITLE
Harvest and properties tables: 'show # of entries' does not work on Safari

### ISSUE THREAD

**Issue by tassia** [tiagovaz/saskatoon#88]
Stays at 10 entries forever. Low priority of course ;)

Bug found on Mac 10.10:
Safari, doesn't work
Firefox, works well

**Comment by RignonNoel** [comment]
Try to get a new version of datatables. But i don't find the problem on the web and it come from the `datatables` dependency

**Comment by tiagovaz** [comment]
It seems the issue happens only in safari, seems not a bug from our side. Closing.
