### ISSUE TITLE
Improvements to the harvest detail page

### ISSUE THREAD

**Issue by tassia** [tiagovaz/saskatoon#97]

**Comment by tassia** [comment]
* Variable hight for comments
* Remove history for non-authenticated users
* Add total harvest yield

**Comment by tiagovaz** [comment]
Done:

* Remove history for non-authenticated users
* Change lable "Notes about this harvest" to "public announcement"

**Comment by tiagovaz** [comment]
Please someone help with variable height for comments panel.

**Comment by tiagovaz** [comment]
Done: _Add total harvest yield_ 

Via a method in harvest model.

**Comment by tiagovaz** [comment]
All done!
